config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    resources :items, controller: 'orders/items', only: [:index]
  end
  resources :products
  resources :buyers
  root 'home#index'
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
end

# == Schema Information
#
# Table name: buyers
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  city       :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :buyer
  has_many :items, class_name: 'OrderItem'
  has_many :products, through: :items

  def total
    items.joins(:product).sum('order_items.quantity * products.price')
  end

  def items_count
    items.count
  end
end

# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  buyer_id   :integer
#  date       :date
#  payment    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_orders_on_buyer_id  (buyer_id)
#

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  def sub_total
    @sub_total ||= quantity * product.price
  end
end

# == Schema Information
#
# Table name: order_items
#
#  id         :integer          not null, primary key
#  order_id   :integer
#  product_id :integer
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_order_items_on_order_id    (order_id)
#  index_order_items_on_product_id  (product_id)
#

app/models/product.rb
class Product < ActiveRecord::Base
end

# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  price       :float
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all.order(:name)
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:name, :address, :city)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders/items_controller.rb
class Orders::ItemsController < ApplicationController
  def index
    @items = order.items.joins(:product)
  end

  private

  def order
    @order ||= Order.find(params[:order_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.includes(:buyer, :items).all.order(:date).page(page).per(per_page)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  helper_method :page
  helper_method :per_page

  private
    def page
      params[:page] || 1
    end

    def per_page
      params[:per_page] || 10
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:buyer_id, :payment)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/buyers/_form.html.slim
= form_for @buyer do |f|
  - if @buyer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@buyer.errors.count, "error")} prohibited this buyer from being saved:"
      ul
        - @buyer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :city
    = f.text_field :city
  .actions = f.submit

app/views/buyers/edit.html.slim
h1 Editing buyer

== render 'form'

= link_to 'Show', @buyer
'|
= link_to 'Back', buyers_path

app/views/buyers/index.html.slim
h1 Listing buyers

table
  thead
    tr
      th Name
      th Address
      th City
      th
      th
      th

  tbody
    - @buyers.each do |buyer|
      tr
        td = buyer.name
        td = buyer.address
        td = buyer.city
        td = link_to 'Show', buyer
        td = link_to 'Edit', edit_buyer_path(buyer)
        td = link_to 'Destroy', buyer, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Buyer', new_buyer_path

app/views/buyers/new.html.slim
h1 New buyer

== render 'form'

= link_to 'Back', buyers_path

app/views/buyers/show.html.slim
p#notice = notice

p
  strong Name:
  = @buyer.name
p
  strong Address:
  = @buyer.address
p
  strong City:
  = @buyer.city

= link_to 'Edit', edit_buyer_path(@buyer)
'|
= link_to 'Back', buyers_path

app/views/home/index.html.slim
= react_component('Dashboard')

app/views/layouts/application.html.slim
doctype html
html
  head
    title Kikker
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.skin-green.sidebar-collapse
    .wrapper
      header.main-header
        = link_to root_path, class: 'logo' do
          span.logo-lg React-POC
        = render 'shared/navigation'
      .content-wrapper
        section.content-header = render 'shared/messages'
        section class="content-header"
          h1
            = content_for?(:title) ? yield(:title) : t(controller_name)
            - if content_for?(:subtitle)
              span = yield(:subtitle)
        section.content
          .row
            .col-xs-12
              .box
                .box-body
                  = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    / - if exist_js_file_to_controller?
    /  = javascript_include_tag controller_name

app/views/orders/_form.html.slim
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :buyer
    = f.text_field :buyer
  .field
    = f.label :payment
    = f.text_field :payment
  .actions = f.submit

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

= link_to 'Show', @order
'|
= link_to 'Back', orders_path

app/views/orders/index.html.slim
h1 Listing orders

table
  thead
    tr
      th Buyer
      th Payment
      th
      th
      th

  tbody
    - @orders.each do |order|
      tr
        td = order.buyer
        td = order.payment
        td = link_to 'Show', order
        td = link_to 'Edit', edit_order_path(order)
        td = link_to 'Destroy', order, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Order', new_order_path

app/views/orders/new.html.slim
h1 New order

== render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.slim
p#notice = notice

p
  strong Buyer:
  = @order.buyer
p
  strong Payment:
  = @order.payment

= link_to 'Edit', edit_order_path(@order)
'|
= link_to 'Back', orders_path

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :price
    = f.text_field :price
  .actions = f.submit

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Show', @product
'|
= link_to 'Back', products_path

app/views/products/index.html.slim
h1 Listing products

table
  thead
    tr
      th Name
      th Description
      th Price
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.description
        td = product.price
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product', new_product_path

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name
p
  strong Description:
  = @product.description
p
  strong Price:
  = @product.price

= link_to 'Edit', edit_product_path(@product)
'|
= link_to 'Back', products_path

app/views/shared/_messages.html.slim
- flash.each do |name, msg|
  - name = name.to_s == 'notice' ? 'info' : (name.to_s == 'error' || name.to_s == 'alert' ? 'danger' : name.to_s)
  - icon = name == 'danger'  ? 'ban'     : nil
  - icon = name == 'info'    ? 'info'    : icon
  - icon = name == 'warning' ? 'warning' : icon
  - icon = name == 'success' ? 'check'   : icon
  - if msg.is_a?(String)
    div class="alert alert-#{name}"
      button type="button" class="close" data-dismiss="alert" aria-hidden="true"
        ' &times;
      div id="flash_#{name}">
        = fa_icon icon, class: 'icon'
        = msg

app/views/shared/_navigation.html.slim
nav class="navbar navbar-static-top" role="navigation"
  .navbar-custom-menu id="top_menu"
    ul class="nav navbar-nav"
      / li class="class_if_active(root_path)"
      /   = link_to root_path do
      /     = fa_icon 'dashboard'
      /     ' Home